[2022-02-05 21:14:58,999] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2020-02-02T06:00:00+00:00 [queued]>
[2022-02-05 21:14:59,149] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2020-02-02T06:00:00+00:00 [queued]>
[2022-02-05 21:14:59,153] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-05 21:14:59,156] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-02-05 21:14:59,158] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-05 21:27:20,360] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2020-02-02 06:00:00+00:00
[2022-02-05 21:27:20,481] {standard_task_runner.py:52} INFO - Started process 2337 to run task
[2022-02-05 21:27:20,622] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'scheduled__2020-02-02T06:00:00+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dags_hw.py', '--cfg-path', '/tmp/tmpl3_go1xt', '--error-file', '/tmp/tmphtzotfqb']
[2022-02-05 21:27:20,660] {standard_task_runner.py:77} INFO - Job 127: Subtask download_dataset_task
[2022-02-05 21:27:21,187] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2020-02-02T06:00:00+00:00 [running]> on host 6aa22590a839
[2022-02-05 21:27:21,477] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-05 21:27:21,552] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2020-02-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-02T06:00:00+00:00
[2022-02-05 21:27:21,556] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-05 21:27:21,581] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sS https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2020-02.csv > /opt/***/yellow_tripdata_2020-02.csv']
[2022-02-05 21:27:21,835] {subprocess.py:85} INFO - Output:
[2022-02-05 21:27:41,618] {local_task_job.py:212} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-02-05 21:27:41,626] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 2337. PIDs of all processes in the group: [2341, 2342, 2337]
[2022-02-05 21:27:41,634] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 2337
[2022-02-05 21:27:41,635] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-02-05 21:27:41,638] {subprocess.py:99} INFO - Sending SIGTERM signal to process group
[2022-02-05 21:27:42,352] {process_utils.py:70} INFO - Process psutil.Process(pid=2337, status='terminated', exitcode=0, started='21:27:20') (2337) terminated with exit code 0
[2022-02-05 21:27:42,355] {process_utils.py:70} INFO - Process psutil.Process(pid=2341, status='terminated', started='21:27:21') (2341) terminated with exit code None
[2022-02-05 21:27:49,472] {process_utils.py:70} INFO - Process psutil.Process(pid=2342, status='terminated', started='21:27:21') (2342) terminated with exit code None
